version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: iot_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-iotdb}
      MYSQL_USER: ${MYSQL_USER:-iotuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-iotpass}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: iot_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: iot_django
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - mosquitto
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "iotsec.asgi:application"]

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: iot_mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/create_passwd.sh:/create_passwd.sh
      - ./mosquitto/certs:/mosquitto/certs
    environment:
      MOSQUITTO_USER: ${MOSQUITTO_USER:-device1}
      MOSQUITTO_PASS: ${MOSQUITTO_PASS:-devpass}
    command: ["sh", "/create_passwd.sh"]
    ports:
      - "1883:1883"
      - "8883:8883"   # TLS
  nodered:
    image: nodered/node-red:latest
    container_name: iot_nodered
    restart: unless-stopped
    ports:
      - "1880:1880"         # Interface Node-RED
    environment:
      - TZ=Africa/Dakar
    depends_on:
      - mosquitto
    volumes:
      - ./nodered_data:/data   # Sauvegarde des flows Node-RED
    # Permet à Node-RED d'accéder au broker interne via: mqtt://mosquitto:1883

volumes:
  db_data:
  nodered_data: